services:
  laravel:
    build: .
    container_name: laravel
    restart: unless-stopped
    ports:
      - "5000:8000"
    volumes:
      - ./:/var/www/html
    networks:
      - laravel
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - laravel
volumes:
  mysql:
    name: mysql
networks:
  laravel:
    name: laravel
